### PR TITLE
Use protocol-relative URIs

### PR DESCRIPTION
**Pull request by Rillke**
Use protocol-relative URIs to avoid browser security warnings. This fixes only those in code. There seem to be some more in the database? http://pastebin.com/r5E46jx2 is a list of those, Firefox complained about **while visiting** the `/register` page.

lgm security warning

### CODE REVIEW

**Comment by aoloe** [comment]
thanks! i'll have a look at it tomorrow...
do you have an example for the problems that might come from the DB?

**Comment by Rillke** [comment]
- http://libregraphicsmeeting.org/2016/wp/wp-content/uploads/2016/03/BW-logo-block_RGB-WEB.png
- http://libregraphicsmeeting.org/2016/wp/wp-content/uploads/2016/01/UoW-logo.jpg

or this is a WordPress configuration...

**Comment by Rillke** [comment]
Nope, I won't resolve merge confilcts. The branch was ahead of your master the exact one commit. Please fix it yourself.

**Comment by aoloe** [comment]
@Rillke, did you have a bad lunch? :-)

at some time during the weekend i'll fix the links, don't worry...
we have no plan to complain with you because a reather simple pull request does not cleanly merge anymore!

peace and love
a.l.e

**Comment by Rillke** [comment]
> did you have a bad lunch? :-)

No, it's just not worth starting merge for such a simple change. Just fix it, and I'll be happy :)

**Comment by aoloe** [comment]
the cases in your PR have been fixed in a different way, by using relative paths instead of absolute ones (which is -- i guess -- a best practice in WP).

i've fixed the two other cases you listed (plus the other links in the sponsors sidebar). they are edited by hand by our editors and, i hope, they are adding sponsors through copy paste and the future links will (i hope) be a copy paste of the current ones...

in the content it's a bit harder...
i've opened a ticket for it!

https://github.com/libregraphicsmeeting/htdocs-2016/issues/18

ciao & thanks for reporting!

**Pull request closed without merging**
